### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by myuon** [myuon/quartz#7]
## Language
- [x] modules
- [x] function
- [x] struct
- [ ] methods
  - [x] method calls by value
  - [ ] method calls by reference
- [ ] closure, revised
- [x] tuple
- [x] pointer with ref type: pointer will not be supported
- [ ] bytes (for arrays)

## Semantics
- [x] static function/variable
- [ ] sizeof based pointer calculation

## Optimizations
